name: Deploy to production

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            INSTANCE=${{ vars.INSTANCE_PROD }}
            BEEHIIV_API_KEY=${{ secrets.BEEHIIV_API_KEY }}
            BEEHIIV_PUB_ID=${{ secrets.BEEHIIV_PUB_ID }}
            GUMROAD_TOKEN=${{ secrets.GUMROAD_TOKEN }}
            MONGO_URL=${{ secrets.MONGO_URL }}
            MEDIUM_URL=${{ secrets.MEDIUM_URL }}
            UUID_TOKEN=${{ secrets.UUID_TOKEN_PROD }}
          push: true
          tags: '${{ secrets.REGISTRY_URL }}/yng/yngdev-api:latest'
          cache-from: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/yng/yngdev-api:buildcache'
          cache-to: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/yng/yngdev-api:buildcache,mode=max'
